Add composer to Circle CI

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -7,7 +7,7 @@ jobs:
   build:
     docker:
       # specify the version you desire here
-      - image: circleci/php:latest
+      - image: image: circleci/php:7.1
 
       # Specify service dependencies here if necessary
       # CircleCI maintains a library of pre-built images
@@ -15,6 +15,23 @@ jobs:
       # - image: circleci/mysql:9.4
 
     working_directory: ~/repo
+
+    install_composer: &install_composer
+        command: |
+            cd /tmp
+            EXPECTED_SIGNATURE=$(curl -q https://composer.github.io/installer.sig)
+            php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
+            ACTUAL_SIGNATURE=$(php -r "echo hash_file('SHA384', 'composer-setup.php');")
+            if [ "$EXPECTED_SIGNATURE" != "$ACTUAL_SIGNATURE" ]
+            then
+                >&2 echo 'ERROR: Invalid installer signature'
+                rm composer-setup.php
+                exit 1
+            fi
+            sudo php composer-setup.php --quiet --install-dir /usr/local/bin --filename composer
+            RESULT=$?
+            rm composer-setup.php
+            exit $RESULT
 
     steps:
       - checkout
